version: '3.8'

services:
  discovery-service:
    image: discovery-service
    ports:
      - "8761:8761"

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: membersdb

  members-service:
    image: members-service
    ports:
      - "8085:8085"
    environment:
      - DB_URL=mongodb://mongodb:27017/membersdb
      - SERVER_PORT=8085
      - CONTEXT_PATH=/members
      - EUREKA_SERVER=http://discovery-service:8761/eureka/
    depends_on:
      - mongodb
      - discovery-service

  members-servic-2:
    image: members-service
    ports:
      - "8086:8085"
    environment:
      - DB_URL=mongodb://mongodb:27017/membersdb
      - SERVER_PORT=8085
      - CONTEXT_PATH=/members
      - EUREKA_SERVER=http://discovery-service:8761/eureka/
    depends_on:
      - mongodb
      - discovery-service

  postgresspringboot:
    image: postgres:latest
    environment:
      - POSTGRES_DB=pos
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  product-service:
    image: product-service:latest
    environment:
      - DB_URL=jdbc:postgresql://postgresspringboot:5432/pos
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
      - SERVER_PORT=8002
      - CONTEXT_PATH=/products-app/api
      - EUREKA_SERVER=http://discovery-service:8761/eureka/
    ports:
      - "8002:8002"
    depends_on:
      - postgresspringboot
      - discovery-service

volumes:
  postgres-data: