version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-spring-boot
    environment:
      POSTGRES_DB: pos
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  product-service:
    image: product-service:latest
    container_name: product-service
    environment:
      DB_URL: jdbc:postgresql://postgres-spring-boot:5433/pos
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      SERVER_PORT: 8002
      CONTEXT_PATH: /products-app/api
    ports:
      - "8002:8002"
    depends_on:
      - postgres

volumes:
  postgres-data:
